### ISSUE TITLE
[Server Crash][1.5.1+1.18.1] Attempts to use Minecraft client-side only class via Fabric API

### ISSUE THREAD

**Issue by TigerWalts** [HyperPigeon/Gizmos#10]
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'gizmos'!
...
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_6395
at net.hyper_pigeon.Gizmos.Gizmos.onInitialize(Gizmos.java:26) ~[Gizmos-1.5.1+1.18.1.jar:?]
```

`net/minecraft/class_6395` is `net/minecraft/client/item/UnclampedModelPredicateProvider`
- https://github.com/FabricMC/yarn/blob/1.18.1/mappings/net/minecraft/client/item/UnclampedModelPredicateProvider.mapping

Line 26 in `Gizmos.java` uses `net.fabricmc.fabric.api.object.builder.v1.client.model.FabricModelPredicateProviderRegistry`

> Allows registering model predicate providers for item models.

https://github.com/HyperPigeon/Gizmos/blob/fa6554e598ac02e3f8b3f378d5e04186a7c1db51/src/main/java/net/hyper_pigeon/Gizmos/Gizmos.java#L22-L26

**Comment by HyperPigeon** [comment]
fixed in latest release
